sudo: required
services:
  - docker

before_install:
  - docker build -t jamiecha/docker-react -f Dockerfile.dev .

script:
  - docker run jamiecha/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react1"
  env: "React1-env"
  bucket_name: "elasticbeanstalk-us-east-2-621337029218"
  bucket_path: "react1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"